name: build and test feture branch

on:
  pull_request:
    branches: [develop]
    types: [opened, reopened]

jobs:
  build-feature:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3  ###Descargar el codigo fuente
        with:
          ref: ${{ github.event.pull_request.head.sha }} ###Descargar el codigo fuente de la rama en especifico

      - name: pull and ceckout from git repository
        run: |
          echo "pull and ceckout from git repository"

      - name: setup java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: build with maven
        run: |
          mvn clean test package
          echo "build with maven"